# Azure Pipeline JUST for PR checks

trigger:
- main

pr:
- main

jobs:

- job: Build
  condition: eq(variables['Build.Reason'], 'PullRequest')
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True
      win:
        imageName: 'windows-2019'
        isWindows: True
      lin:
        imageName: 'ubuntu-20.04'
        isLinux: True

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1

  - bash: |
      cmake -Bbuild -DCMAKE_BUILD_TYPE=Release
      cmake --build build --config Release
      ./build/test-binary/sst-cpputils-tests
    displayName: Run tests with cmake

- job: Doxygenate
  condition: not(eq(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - checkout: self
    fetchDepth: 1

  - task: DownloadSecureFile@1
    inputs:
      secureFile: sru-token.txt

  - bash: |
       sudo apt-get install doxygen graphviz
       doxygen doxygen/Doxyfile

       HASH=`git rev-parse --short HEAD`
       TOK=`cat $AGENT_TEMPDIRECTORY/sru-token.txt`
       git clone https://surge-rackupdater:${TOK}@github.com/surge-synthesizer/sst-docs
       mkdir -p sst-docs/docs/sst-cpputils
       pushd doxy-out 
       tar cf - . | (cd ../sst-docs/docs/sst-cpputils && tar xf -)
       popd
       pushd sst-docs
       git add docs
       git status
       git commit -m "Update sst-utils docs at ${HASH}"
       
    displayName: "Make Doxygen and Commit it" 
    

